guava-r09-jarjar.jar in $HADOOP_HOME/lib is required for running PerceptronUDTFTest. Otherwise, "java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/guava/common/primitives/UnsignedBytes" is thrown.