Onehot encoding (#357)
* [#294] Implement onehot_encoding UDAF

* Updated hive version dependencies from v0.12.0 to v0.13.0

* Updated onehot_encoding UDAF

* Fixed compilation errors for API changes of Hive v0.13.0

* Avoided NPE in
org.apache.hadoop.hive.conf.HiveConf.getVar(HiveConf.java:1295)

* Ignored a test to support Hive v0.13.0